services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  app:
    build: .
    container_name: caothien2k2/app-nodejs
    ports:
      - "${PORT}:${PORT}"
    env_file: 
      - .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${MGDB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${MGDB_PASSWORD}"
    volumes:
      - mongodb:/data/db
volumes:
  mongodb:
